# Generated by Django 3.2.2 on 2021-05-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=20, null=True)),
                ('jenis_barang', models.CharField(choices=[('KATEGORI 1', 'KATEGORI 1'), ('KATEGORI 2', 'KATEGORI 2'), ('KATEGORI 3', 'KATEGORI 3'), ('KATEGORI 4', 'KATEGORI 4'), ('KATEGORI 5', 'KATEGORI 5'), ('KATEGORI 6', 'KATEGORI 6')], max_length=10, null=True)),
                ('isFound', models.BooleanField(default=False)),
                ('isSolved', models.BooleanField(default=False)),
                ('deskripsi_barang', models.TextField(null=True)),
            ],
            options={
                'db_table': 'barang',
            },
        ),
    ]
