# Generated by Django 3.2.2 on 2021-05-09 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prodi', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Daftar Program Studi',
                'db_table': 'Program-studi',
            },
        ),
        migrations.AlterModelOptions(
            name='barang',
            options={'verbose_name_plural': 'Daftar Barang'},
        ),
        migrations.RemoveField(
            model_name='barang',
            name='deskripsi_barang',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='isFound',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='isSolved',
        ),
        migrations.AlterField(
            model_name='barang',
            name='jenis_barang',
            field=models.CharField(choices=[('Elektronik', 'Elektronik'), ('Alat Tulis', 'Alat Tulis'), ('Buku', 'Buku'), ('Kunci Kendaraan', 'Kunci Kendaraan'), ('KATEGORI 5', 'KATEGORI 5'), ('KATEGORI 6', 'KATEGORI 6')], max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FOUND', 'FOUND'), ('LOST', 'LOST')], max_length=5, null=True)),
                ('isSolved', models.BooleanField(default=False)),
                ('deskripsi_barang', models.TextField(null=True)),
                ('tgl_laporan', models.DateField(auto_now_add=True, null=True)),
                ('lokasi', models.CharField(choices=[('GEDUNG A', 'GEDUNG A'), ('GEDUNG B', 'GEDUNG B'), ('GEDUNG C', 'GEDUNG C'), ('GEDUNG D', 'GEDUNG D'), ('GEDUNG E', 'GEDUNG E'), ('GEDUNG F', 'GEDUNG F'), ('LABTEK 1', 'LABTEK 1'), ('LABTEK 2', 'LABTEK 2'), ('LABTEK 3', 'LABTEK 3'), ('GKU 1', 'GKU 1'), ('LAINNYA', 'LAINNYA')], max_length=10, null=True)),
                ('image', models.ImageField(default='/item/default.png', upload_to='item')),
                ('barang_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='dashboard.barang')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daftar Laporan',
                'db_table': 'laporan',
            },
        ),
    ]
