# Generated by Django 3.2.2 on 2021-05-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210508_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='tgl_laporan',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='jenis_barang',
            field=models.CharField(choices=[('Elektronik', 'Elektronik'), ('KATEGORI 2', 'KATEGORI 2'), ('KATEGORI 3', 'KATEGORI 3'), ('KATEGORI 4', 'KATEGORI 4'), ('KATEGORI 5', 'KATEGORI 5'), ('KATEGORI 6', 'KATEGORI 6')], max_length=10, null=True),
        ),
    ]
