# Generated by Django 3.2.2 on 2021-05-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210510_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodi',
            old_name='nama_prodi',
            new_name='nama_prodis',
        ),
        migrations.AlterModelTable(
            name='prodi',
            table='program-studi',
        ),
    ]
