# Generated by Django 3.2.2 on 2021-05-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210510_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodi',
            old_name='nama_prodis',
            new_name='nama_prodi',
        ),
    ]
