# Generated by Django 3.2.2 on 2021-05-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_nama_prodis_prodi_nama_prodi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='jenis_barang',
            field=models.CharField(choices=[('Elektronik', 'Elektronik'), ('Alat Tulis', 'Alat Tulis'), ('Buku', 'Buku'), ('Kunci Kendaraan', 'Kunci Kendaraan'), ('Alat Kecantikan', 'Alat Kecantikan'), ('Peralatan Komputer', 'Peralatan Komputer'), ('Lainnya', 'Lainnya')], max_length=25, null=True),
        ),
    ]
