# Generated by Django 3.2 on 2021-05-08 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_barang_lokasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='deskripsi_barang',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='isSolved',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='lokasi',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='status',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='tgl_laporan',
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi_barang', models.TextField(null=True)),
                ('tgl_laporan', models.DateField(auto_now_add=True, null=True)),
                ('lokasi', models.CharField(choices=[('GEDUNG A', 'GEDUNG A'), ('GEDUNG B', 'GEDUNG B'), ('GEDUNG C', 'GEDUNG C'), ('GEDUNG D', 'GEDUNG D'), ('GEDUNG E', 'GEDUNG E'), ('GEDUNG F', 'GEDUNG F'), ('LABTEK 1', 'LABTEK 1'), ('LABTEK 2', 'LABTEK 2'), ('LABTEK 3', 'LABTEK 3'), ('GKU 1', 'GKU 1'), ('LAINNYA', 'LAINNYA')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('FOUND', 'FOUND'), ('LOST', 'LOST')], max_length=10, null=True)),
                ('isSolved', models.BooleanField(default=False)),
                ('barang_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='dashboard.barang')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
