# Generated by Django 3.2.2 on 2021-05-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210508_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barang',
            options={'verbose_name_plural': 'Daftar Barang'},
        ),
        migrations.AlterModelOptions(
            name='laporan',
            options={'verbose_name_plural': 'Daftar Laporan'},
        ),
        migrations.AlterField(
            model_name='barang',
            name='jenis_barang',
            field=models.CharField(choices=[('Elektronik', 'Elektronik'), ('Alat Tulis', 'Alat Tulis'), ('Buku', 'Buku'), ('Kunci Kendaraan', 'Kunci Kendaraan'), ('KATEGORI 5', 'KATEGORI 5'), ('KATEGORI 6', 'KATEGORI 6')], max_length=25, null=True),
        ),
        migrations.AlterModelTable(
            name='laporan',
            table='laporan',
        ),
    ]
