# Generated by Django 3.2.2 on 2021-05-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210508_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prodi', models.CharField(choices=[('Teknik Informatika', 'Teknik Informatika'), ('Teknik Elektro', 'Teknik Elektro'), ('Teknologi Pangan', 'Teknologi Pangan'), ('Teknik Geofisika', 'Teknik Geofisika'), ('Teknik Sipil', 'Teknik Sipil'), ('Teknik Arsitektur', 'Teknik Arsitektur'), ('Teknik Mesin', 'Teknik Mesin'), ('Biologi', 'Biologi'), ('Farmasi', 'Farmasi'), ('Perencanaan Wilayah dan Kota', 'Perancangan Wilayah dan Kota'), ('LAINNYA', 'LAINNYA')], max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Daftar Program Studi',
                'db_table': 'Program-studi',
            },
        ),
    ]
