# Generated by Django 3.2.2 on 2021-05-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_prodi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodi',
            name='nama_prodi',
            field=models.CharField(choices=[(1, 'Teknik Informatika'), (2, 'Teknik Elektro'), (3, 'Teknologi Pangan'), (4, 'Teknik Geofisika'), (5, 'Teknik Sipil'), (6, 'Teknik Arsitektur'), (7, 'Teknik Mesin'), (8, 'Biologi'), (9, 'Farmasi'), (10, 'Perencanaan Wilayah dan Kota')], max_length=50, null=True),
        ),
    ]
