# Generated by Django 3.2.2 on 2021-05-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_prodi_nama_prodi'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='image',
            field=models.ImageField(default='/item/default.png', upload_to='item'),
        ),
    ]
