# Generated by Django 3.2.2 on 2021-05-09 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20210510_0201'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIP', models.CharField(max_length=20)),
                ('Jabatan', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daftar Staff & Dosen',
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIM', models.CharField(max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daftar Mahasiswa',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.CharField(max_length=200)),
                ('no_telp', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(default='/profile_images/avatar.png', upload_to='profile_images')),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
                ('prodi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='dashboard.prodi')),
            ],
            options={
                'verbose_name_plural': 'Daftar User Profile',
                'db_table': 'user-profile',
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
