# Generated by Django 3.2.2 on 2021-05-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210510_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(default='/profile_images/avatar.jpg', upload_to='profile_images'),
        ),
    ]
