# Generated by Django 3.2.2 on 2021-05-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210509_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile',
            options={'verbose_name_plural': 'Daftar User Profile'},
        ),
        migrations.AlterModelTable(
            name='user_profile',
            table='user-profile',
        ),
    ]
