# Generated by Django 3.2.2 on 2021-05-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_student_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user_id',
            new_name='user',
        ),
    ]
