# Generated by Django 3.2.2 on 2021-05-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210509_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Daftar Staff & Dosen'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Daftar Mahasiswa'},
        ),
        migrations.AlterModelTable(
            name='staff',
            table='staff',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
