# Generated by Django 3.2.2 on 2021-05-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210509_1511'),
        ('user', '0008_rename_prodi_id_user_profile_prodi'),
    ]

    operations = [
    ]
