# Generated by Django 3.2.2 on 2021-05-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='account',
            new_name='user',
        ),
    ]
