# Generated by Django 3.2.2 on 2021-05-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_account_user_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='user',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='user',
            new_name='account',
        ),
    ]
