# Generated by Django 3.2.2 on 2021-05-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210509_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='account',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='account',
            new_name='user',
        ),
    ]
